### ISSUE TITLE
App Crashes

### ISSUE THREAD

**Issue by zararani** [Eesha-Jain/BioMatrix#6]
App get crashed on start

**Comment by Eesha-Jain** [comment]
How are you running the program? Did you download the code and testing it on a personal device?

**Comment by zararani** [comment]
> How are you running the program? Did you download the code and testing it on a personal device?
yes i have downlod the code and run on my real device. after lunch the app when click on start button app will crashed

**Comment by Eesha-Jain** [comment]
Are you testing on an Android or iPhone?

**Comment by zararani** [comment]
> Are you testing on an Android or iPhone?

I’m testing on iPhone

**Comment by Eesha-Jain** [comment]
Can you screenshot or send the error message you are getting?

**Comment by zararani** [comment]
> Can you screenshot or send the error message you are getting?

Swift/Integers.swift:2667: Fatal error: Can't get random value with an empty range
<img width="1152" alt="Screenshot 2021-09-22 at 12 28 56 PM" src="https://user-images.githubusercontent.com/76549774/134301185-cc137b93-f057-497d-8f41-2c5654af0f48.png">
2021-09-22 12:27:45.893857+0500 BioMatrix[21405:5773623] Swift/Integers.swift:2667: Fatal error: Can't get random value with an empty range
(lldb)

**Comment by Eesha-Jain** [comment]
Looks like the code was not completely updated on Github. I repushed it. Would it be possible to redownload and see whether it works now?

**Comment by zararani** [comment]
> Looks like the code was not completely updated on Github. I repushed it. Would it be possible to redownload and see whether it works now?

Yes please repush and let me know

**Comment by Eesha-Jain** [comment]
Okay, repushed. You can try now

**Comment by Eesha-Jain** [comment]
Looks like you haven't responded in a while, so I'm gonna assume that things are working now. Have a great day!
